<#
.SYNOPSIS
  foundryLab Phase 0 deploy script.

.DESCRIPTION
  Idempotent provisioning of the shared Foundry account, project, model deployments,
  observability, and managed identity.

  Steps:
    1. Preflight: confirm subscription, region, signed-in user, model quota
    2. Create resource group (if missing)
    3. Run `az deployment group what-if` and pause for review (unless -SkipWhatIf)
    4. Deploy main.bicep
    5. Capture outputs and write them to ../../.env (gitignored)

.EXAMPLE
  ./deploy.ps1                 # full flow including what-if review
  ./deploy.ps1 -SkipWhatIf     # for re-runs after first deploy
  ./deploy.ps1 -DryRun         # what-if only, no deploy

.NOTES
  Requires: az CLI logged in to the Visual Studio Enterprise subscription.
  Region: swedencentral (chat + embedding consumption SKUs).
#>

[CmdletBinding()]
param(
  [string]$SubscriptionName = 'Visual Studio Enterprise Subscription',
  [string]$ResourceGroupName = 'foundrylab-rg',
  [string]$Location = 'swedencentral',
  [string]$DeploymentName = "foundrylab-phase0-$(Get-Date -Format 'yyyyMMddHHmm')",
  [switch]$SkipWhatIf,
  [switch]$DryRun
)

$ErrorActionPreference = 'Stop'
$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$bicepFile = Join-Path $scriptRoot 'main.bicep'
$bicepParamFile = Join-Path $scriptRoot 'main.bicepparam'
$envFile = Join-Path $scriptRoot '..\..\.env'

function Write-Step($msg) {
  Write-Host ""
  Write-Host "==> $msg" -ForegroundColor Cyan
}

# 1. Preflight
Write-Step 'Preflight checks'

az account set --subscription $SubscriptionName 1>$null
$currentSub = az account show --query "{name:name, id:id, user:user.name}" -o json | ConvertFrom-Json
Write-Host "  Subscription: $($currentSub.name)"
Write-Host "  Sub ID:       $($currentSub.id)"
Write-Host "  Signed in as: $($currentSub.user)"

if ($currentSub.name -ne $SubscriptionName) {
  throw "Wrong subscription. Expected '$SubscriptionName', got '$($currentSub.name)'."
}

$ownerObjectId = az ad signed-in-user show --query id -o tsv
if (-not $ownerObjectId) {
  throw "Could not resolve signed-in user object ID. Run 'az login' first."
}
Write-Host "  Owner objectId: $ownerObjectId"

Write-Host "  Region:       $Location"
Write-Host "  Resource grp: $ResourceGroupName"

# Quota sanity check
Write-Host ""
Write-Host "  Quota in ${Location}:"
$usage = az cognitiveservices usage list --location $Location -o json | ConvertFrom-Json
foreach ($key in @('OpenAI.GlobalStandard.gpt-4o-mini','OpenAI.GlobalStandard.text-embedding-3-large')) {
  $q = $usage | Where-Object { $_.name.value -eq $key }
  if ($q) {
    Write-Host ("    {0,-50} {1}/{2}" -f $key, [int]$q.currentValue, [int]$q.limit)
  }
}

# 2. Resource group
Write-Step "Resource group"
$rgExists = az group exists --name $ResourceGroupName | ConvertFrom-Json
if ($rgExists) {
  Write-Host "  Already exists."
} else {
  Write-Host "  Creating $ResourceGroupName in $Location..."
  az group create --name $ResourceGroupName --location $Location `
    --tags project=foundrylab environment=shared managedBy=bicep 1>$null
}

# 3. What-if
if (-not $SkipWhatIf) {
  Write-Step "Dry run (what-if)"
  az deployment group what-if `
    --resource-group $ResourceGroupName `
    --template-file $bicepFile `
    --parameters $bicepParamFile `
    --parameters ownerObjectId=$ownerObjectId

  if ($DryRun) {
    Write-Host ""
    Write-Host "DryRun complete — exiting before deploy." -ForegroundColor Yellow
    return
  }

  Write-Host ""
  $confirm = Read-Host "Proceed with deployment? (y/N)"
  if ($confirm -ne 'y' -and $confirm -ne 'Y') {
    Write-Host "Aborted." -ForegroundColor Yellow
    return
  }
}

# 4. Deploy
Write-Step "Deploying $DeploymentName"
az deployment group create `
  --resource-group $ResourceGroupName `
  --name $DeploymentName `
  --template-file $bicepFile `
  --parameters $bicepParamFile `
  --parameters ownerObjectId=$ownerObjectId `
  --output none

if ($LASTEXITCODE -ne 0) {
  throw "Deployment failed."
}

# Fetch outputs separately to avoid mixing CLI warnings with deploy JSON
$outputsJson = az deployment group show `
  --resource-group $ResourceGroupName `
  --name $DeploymentName `
  --query properties.outputs `
  --output json
$outputs = $outputsJson | ConvertFrom-Json

# 5. Write .env
Write-Step "Writing outputs to $envFile"
$lines = @(
  "# Generated by foundryLab/shared/infrastructure/deploy.ps1"
  "# DO NOT COMMIT — gitignored"
  "AZURE_SUBSCRIPTION_ID=$($currentSub.id)"
  "AZURE_TENANT_ID=$(az account show --query tenantId -o tsv)"
  "AZURE_RESOURCE_GROUP=$ResourceGroupName"
  "AZURE_LOCATION=$Location"
  ""
  "FOUNDRY_PROJECT_ENDPOINT=$($outputs.projectEndpoint.value)"
  "FOUNDRY_PROJECT_RESOURCE_ID=$($outputs.projectResourceId.value)"
  "FOUNDRY_AI_SERVICES_ID=$($outputs.aiServicesAccountId.value)"
  "FOUNDRY_PROJECT_NAME=foundrylab"
  ""
  "FOUNDRY_DEFAULT_DEPLOYMENT=$($outputs.chatDeploymentName.value)"
  "FOUNDRY_EMBED_DEPLOYMENT=$($outputs.embedDeploymentName.value)"
  ""
  "APPLICATIONINSIGHTS_CONNECTION_STRING=$($outputs.appInsightsConnectionString.value)"
  "AZURE_LOG_ANALYTICS_WORKSPACE_ID=$($outputs.logAnalyticsWorkspaceId.value)"
  ""
  "AZURE_CLIENT_ID=$($outputs.managedIdentityClientId.value)"
  "AZURE_MANAGED_IDENTITY_RESOURCE_ID=$($outputs.managedIdentityResourceId.value)"
)
$lines -join "`n" | Set-Content -Path $envFile -Encoding utf8

Write-Step "Done"
Write-Host "  Project endpoint: $($outputs.projectEndpoint.value)"
Write-Host "  Chat deployment:  $($outputs.chatDeploymentName.value)"
Write-Host "  Embed deployment: $($outputs.embedDeploymentName.value)"
Write-Host ""
Write-Host "Next: open Foundry portal → https://ai.azure.com/ → select foundrylab project" -ForegroundColor Green
